// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsln0cassUFhpVYo-SLKkmK7Evw3gpEOs',
    appId: '1:138543873150:web:f965d107420b88dc8e6c2f',
    messagingSenderId: '138543873150',
    projectId: 'lycian-way-trekking',
    authDomain: 'lycian-way-trekking.firebaseapp.com',
    databaseURL: 'https://lycian-way-trekking-default-rtdb.firebaseio.com',
    storageBucket: 'lycian-way-trekking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADeF-4JXq6AcnMMZHvznUPSrzdS5KjGyM',
    appId: '1:138543873150:android:b538b5e50e87b9fb8e6c2f',
    messagingSenderId: '138543873150',
    projectId: 'lycian-way-trekking',
    databaseURL: 'https://lycian-way-trekking-default-rtdb.firebaseio.com',
    storageBucket: 'lycian-way-trekking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhExguwpLiwEcOxPFpbNagBrZaaT45Yg',
    appId: '1:138543873150:ios:8ba9017bca76b4ea8e6c2f',
    messagingSenderId: '138543873150',
    projectId: 'lycian-way-trekking',
    databaseURL: 'https://lycian-way-trekking-default-rtdb.firebaseio.com',
    storageBucket: 'lycian-way-trekking.appspot.com',
    iosClientId: '138543873150-me0281p2qklbbfd7a6mvf2uv8h7e8e2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.restartProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOhExguwpLiwEcOxPFpbNagBrZaaT45Yg',
    appId: '1:138543873150:ios:8ec3bee6740d7ae98e6c2f',
    messagingSenderId: '138543873150',
    projectId: 'lycian-way-trekking',
    databaseURL: 'https://lycian-way-trekking-default-rtdb.firebaseio.com',
    storageBucket: 'lycian-way-trekking.appspot.com',
    iosClientId: '138543873150-85qfegudb52er183bt11c6it6f49pt03.apps.googleusercontent.com',
    iosBundleId: 'com.example.restartProject.RunnerTests',
  );
}
